# Navidrome Configuration
# All info: https://www.navidrome.org/docs/usage/configuration-options/#available-options

AutoTranscodeDownload = false               # By default is false but I want to keep it explicit
DataFolder = "/data"                        # Same as before
DbPath = "/data/navidrome.db?cache=shared&_busy_timeout=30000&_journal_mode=WAL&_foreign_keys=on&synchronous=normal"    # busy timeout set to 30 seconds instead of 15
DefaultLanguage = "es"
DefaultShareExpiration = "48h"              # 2 days
DefaultTheme = "Nord"
EnableGravatar = true
EnableInsightsCollector = true              # Default, but keep it true to collect insights
EnableSharing = true
ImageCacheSize = "2GB"
LogLevel = "info"                           # Keep it at info
MusicFolder = "/music"                      # Default music folder
SessionTimeout = "48h"                      # 48 hours, default
TranscodingCacheSize = "100MB"
UIWelcomeMessage = "Gracias por estar aqu√≠"

# More concurrency
DevArtworkMaxRequests = 0 
# Largest queue before error
DevArtworkThrottleBacklogLimit = 500

[Backup]
Count = 5
Schedule =  "0 4 * * 2,4,0" # Every Tuesday, Thursday and Sunday at 4AM

[Deezer]
Enabled = true

[Jukebox]
Enabled = false # Let's take a look at this later

[LastFM]
Enabled = true

[Prometheus]
Enabled = true

[Scanner]
Enabled = true
ScanOnStartup = true
PurgeMissing = "always" # Remove missing files on every scan
Schedule = "0 * * * *"  # Every hour
WatcherWait = "1m"
